import { supabaseServer } from "@/lib/supabase";
import { FileText, Download } from "lucide-react";

export const dynamic = "force-dynamic";

export default async function ReportsPage() {
  const sb = supabaseServer();
  const { data: reports } = await sb
    .from("reports")
    .select("id, period_start, period_end, narrative, pptx_url, pdf_url, generated_at")
    .order("generated_at", { ascending: false })
    .limit(20);

  return (
    <div className="space-y-6">
      <div className="flex items-end justify-between">
        <div>
          <h1 className="text-3xl font-semibold">Reports</h1>
          <p className="text-sm text-slate-400">Weekly executive narratives + branded decks, generated by the pipeline.</p>
        </div>
        <form action="/api/generate-report" method="POST">
          <button className="rounded-md bg-brand-500 px-4 py-2 text-sm font-medium text-white hover:bg-brand-600">
            Generate now
          </button>
        </form>
      </div>

      <div className="space-y-4">
        {reports?.length ? (
          reports.map((r) => (
            <article key={r.id} className="rounded-xl border border-white/5 bg-[var(--panel)] p-5">
              <header className="mb-3 flex items-center justify-between">
                <div className="flex items-center gap-2 text-sm text-slate-300">
                  <FileText size={16} />
                  {new Date(r.period_start).toLocaleDateString()} – {new Date(r.period_end).toLocaleDateString()}
                </div>
                <div className="flex gap-2">
                  {r.pdf_url && (
                    <a href={r.pdf_url} className="flex items-center gap-1 text-xs text-brand-500 hover:underline">
                      <Download size={14} /> PDF
                    </a>
                  )}
                  {r.pptx_url && (
                    <a href={r.pptx_url} className="flex items-center gap-1 text-xs text-brand-500 hover:underline">
                      <Download size={14} /> PPTX
                    </a>
                  )}
                </div>
              </header>
              <p className="whitespace-pre-line text-sm leading-relaxed text-slate-300">
                {(r.narrative ?? "").slice(0, 600)}
                {(r.narrative ?? "").length > 600 ? "…" : ""}
              </p>
            </article>
          ))
        ) : (
          <p className="text-sm text-slate-500">No reports yet — click <em>Generate now</em> to run the pipeline.</p>
        )}
      </div>
    </div>
  );
}
